// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoFinalApis.Data;

#nullable disable

namespace TrabajoFinalApis.Migrations
{
    [DbContext(typeof(TrabajoFinalApisContext))]
    [Migration("20251128151931_lol")]
    partial class lol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TrabajoFinalApis.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Todo tipo de pizzas",
                            IsActive = true,
                            Name = "Pizzas",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gaseosas y cervezas",
                            IsActive = true,
                            Name = "Bebidas",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Helados y tortas",
                            IsActive = true,
                            Name = "Postres",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tacos clásicos",
                            IsActive = true,
                            Name = "Tacos",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Burritos grandes",
                            IsActive = true,
                            Name = "Burritos",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gaseosas y aguas",
                            IsActive = true,
                            Name = "Bebidas",
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HappyHourEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HappyHourStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHappyHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Pizza de mozzarella y aceitunas",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = true,
                            IsHappyHour = false,
                            Name = "Pizza Mozzarella",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Mozzarella, tomate y ajo",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = false,
                            IsHappyHour = false,
                            Name = "Pizza Napolitana",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Gaseosa Coca-Cola",
                            DiscountPercentage = 25m,
                            IsAvailable = true,
                            IsFavorite = false,
                            IsHappyHour = true,
                            Name = "Coca-Cola 1.5L",
                            Price = 500m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Postre italiano",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = true,
                            IsHappyHour = false,
                            Name = "Tiramisú",
                            Price = 700m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Taco de carne molida y queso",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = true,
                            IsHappyHour = false,
                            Name = "Taco de Carne",
                            Price = 600m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Taco de pollo desmechado",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = false,
                            IsHappyHour = false,
                            Name = "Taco de Pollo",
                            Price = 550m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "Burrito de frijoles, carne y arroz",
                            DiscountPercentage = 50m,
                            IsAvailable = true,
                            IsFavorite = true,
                            IsHappyHour = true,
                            Name = "Burrito Clásico",
                            Price = 900m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Description = "Botella de agua",
                            DiscountPercentage = 0m,
                            IsAvailable = true,
                            IsFavorite = false,
                            IsHappyHour = false,
                            Name = "Agua sin gas 500ml",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "avenida 212",
                            IsActive = true,
                            Phone = "3464552",
                            RestaurantName = "PizzaLol",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Paraguay 1950",
                            IsActive = true,
                            Phone = "34652255",
                            RestaurantName = "TacoBell",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "matiasdemaria9@gmail",
                            FirstName = "Matias",
                            IsActive = true,
                            LastName = "Demaria",
                            PasswordHash = "lol",
                            Username = "matiasldemaria"
                        },
                        new
                        {
                            Id = 2,
                            Email = "gonzalovicente@gmail.com",
                            FirstName = "Gonzalo",
                            IsActive = true,
                            LastName = "Vicente",
                            PasswordHash = "wow",
                            Username = "gonzalovicente"
                        });
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Category", b =>
                {
                    b.HasOne("TrabajoFinalApis.Entities.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Product", b =>
                {
                    b.HasOne("TrabajoFinalApis.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Restaurant", b =>
                {
                    b.HasOne("TrabajoFinalApis.Entities.User", "User")
                        .WithMany("Restaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.Restaurant", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("TrabajoFinalApis.Entities.User", b =>
                {
                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
